name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: self-hosted

    env:
      RUNRIGHT_API_KEY: ${{ secrets.RUNRIGHT_API_KEY }}
      RUNRIGHT_BIN: ${{ secrets.RUNRIGHT_BIN_PATH }}
      RUNRIGHT_URL: ${{ secrets.RUNRIGHT_URL }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "24"

      - name: Install dependencies
        uses: gbudjeakp/run-right@v1.2.2
        with:
          run: npm ci
          version: v1.2.2
          export: http
          http-url: ${{ secrets.RUNRIGHT_URL }}
          job-id: devops-learn-install-${{ github.run_number }}

      - name: Lint
        uses: gbudjeakp/run-right@v1.2.2
        with:
          run: npm run lint
          version: v1.2.2
          export: http
          http-url: ${{ secrets.RUNRIGHT_URL }}
          job-id: devops-learn-lint-${{ github.run_number }}

      - name: Test
        uses: gbudjeakp/run-right@v1.2.2
        with:
          run: npm run test:run
          version: v1.2.2
          export: http
          http-url: ${{ secrets.RUNRIGHT_URL }}
          job-id: devops-learn-test-${{ github.run_number }}

      - name: Build
        uses: gbudjeakp/run-right@v1.2.2
        with:
          run: npm run build
          version: v1.2.2
          export: http
          http-url: ${{ secrets.RUNRIGHT_URL }}
          job-id: devops-learn-build-${{ github.run_number }}
